language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_script: cd DressHub
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository/'
    - '$HOME/.gradle'

script: "./gradlew clean build"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dresshub-deploy 
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Newone-jeju/DressHub #Github 주소
      branch: master



# CI 알람
notifications:
  email:
    recipients:
      - spear131121@gmail.com
