language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_script: cd DressHub
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository/'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r newone-dresshub *
  - mkdir -p deploy
  - mv newone-dresshub.zip deploy/newone-dresshub.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dresshub-deploy 
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: Newone-jeju/DressHub #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: dresshub-deploy # S3 버킷
    key: newone-dresshub.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: dresshub # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: dresshub-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Newone-jeju/DressHub #Github 주소
      branch: master


# CI 알람
notifications:
  email:
    recipients:
      - spear131121@gmail.com
